### PR TITLE
Updated Jenkins Docker to include rvm, ruby and gulp.

### PR DESCRIPTION
**Pull request by sunshinemu**
I was able to test my job on a local instance of this docker version. Everything works yeah!

### CODE REVIEW

**Comment by zenchicken** [comment]
Why is this exposing port 22?

**Comment by sunshinemu** [comment]
I didn't add that I dont think.

**Comment by sunshinemu** [comment]
Guess I did - removed it sorry!

**Comment by zenchicken** [comment]
👍

**Pull request merged**
